version: "3"
services:
  db:
    image: postgres:15
    volumes:
      - /docker/joplindb:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    image: joplin/server:latest
    depends_on:
      - db
    ports:
      - ${JOPLIN_PORT}:22300
    restart: unless-stopped
    environment:
      - APP_PORT=${JOPLIN_PORT}
      - APP_BASE_URL=${JOPLIN_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db
      - MAILER_ENABLED=${MAILER_ENABLED}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_SECURE=${MAILER_SECURE}
      - MAILER_AUTH_USER=${MAILER_AUTH_USER}
      - MAILER_AUTH_PASSWORD=${MAILER_AUTH_PASSWORD}
      - MAILER_NOREPLY_NAME=${MAILER_NOREPLY_NAME}
      - MAILER_NOREPLY_EMAIL=${MAILER_NOREPLY_EMAIL}
volumes:
  joplindb: null
networks: {}
