version: "3"
services:
  ms:
    image: metasploitframework/metasploit-framework:latest
    container_name: metasploit
    environment:
      DATABASE_URL: postgres://postgres:pplixpp2@172.24.0.2:5432/msf?pool=200&timeout=5
    #      DATABASE_URL: postgres://postgres:pplixpp2@db:5432/msf?pool=200&timeout=5
    links:
      - db
    ports:
      - 4444:4444
    volumes:
      - ./msf:/home/msf/.msf4
      - ./data:/tmp/data
    restart: always
  db:
    image: postgres:11-alpine
    #    image: postgres:15
    #    container_name: meta-db
    #    ports:
    #      - "127.0.0.1:5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pplixpp2
      POSTGRES_USER: postgres
      POSTGRES_DB: msf
    restart: always
networks: {}

#      POSTGRES_HOST_AUTH_METHOD: trust
