services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall-3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
    ports:
      - 9981:80
      - 11443:443
    restart: unless-stopped
networks: {}
