version: "3.9"
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - 8089:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
