version: "3.3"
services:
  uptime-kuma:
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma-data:/app/data  # Local folder mapped to container volume
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
volumes: {}
networks: {}
