services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage2
    ports:
      - 3002:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
networks: {}
